<?php /** @var StuntCoders_AdWordsConversion_Block_Success $this */?>
<script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = <?php echo $this->getConversionId(); ?>;
    var google_conversion_language = "<?php echo $this->getLanguage(); ?>";
    var google_conversion_format = "<?php echo $this->getConversionFormat(); ?>";
    var google_conversion_color = "<?php echo $this->getColor(); ?>";
    var google_conversion_label = "<?php echo $this->getLabel(); ?>";
    var google_conversion_value = <?php echo $this->getGrandTotal() ?: 0.00; ?>;
    var google_conversion_currency = "<?php echo $this->getCurrency() ?: 'EUR'; ?>";
    var google_remarketing_only = <?php echo $this->isGoogleRemarketingOnly(); ?>;
    /* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
    <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/<?php echo $this->getConversionId(); ?>/?value=<?php echo $this->getGrandTotal(); ?>&amp;currency_code=<?php echo $this->getGrandTotal(); ?>&amp;label=<?php echo $this->getLabel(); ?>&amp;guid=ON&amp;script=0"/>
    </div>
</noscript>
